[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "whisky"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whistle_lexer = { git = "https://github.com/MierenManz/whistle", branch = "imports"}
whistle_parser = { git = "https://github.com/MierenManz/whistle", branch = "imports"}
whistle_common = { git = "https://github.com/MierenManz/whistle", branch = "imports"}
whistle_ast = { git = "https://github.com/MierenManz/whistle", branch = "imports"}
whistle_compiler = { git = "https://github.com/MierenManz/whistle", branch = "imports"}
whistle_preprocessor = { git = "https://github.com/MierenManz/whistle", branch = "imports"}
clap = { version = "4.0.29", features = ["derive"]}
wabt = "0.9.1"
